window_prefix: wt-

nerdfont: true
agent: opencode

status_format: false

pre_remove:
  - sh -lc 'oc-cleanup kill >/dev/null 2>&1 || true'

panes:
  - command: nvim .
  - command:
    split: vertical
    size: 10
  - command: opencode --port
    split: horizontal
    focus: true
    target: 0
